# Generated by Django 5.0 on 2025-02-16 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania', models.CharField(default='Nombre de la compañía', max_length=255, unique=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_de_negocio', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFormEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania', models.CharField(default='Nombre de la compañía', max_length=255, unique=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_de_negocio', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_de_quien_registra', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania', models.CharField(max_length=255, unique=True)),
                ('registro_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetSearch.registroform', to_field='nombre_compania')),
                ('registro_form_empresarial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetSearch.registroformempresarial', to_field='nombre_compania')),
            ],
        ),
    ]
