# Generated by Django 5.0 on 2024-04-08 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroformularioempresarial',
            name='tipo_de_negocio',
            field=models.CharField(blank=True, null=True, max_length=75),
            preserve_default=False,
        ),
    ]
