# Generated by Django 5.0 on 2025-02-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0002_alter_registrofinal_registro_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroform',
            name='nombre_compania',
            field=models.CharField(default='Nombre de la compañía', max_length=255),
        ),
        migrations.AlterField(
            model_name='registroformempresarial',
            name='nombre_compania',
            field=models.CharField(default='Nombre de la compañía', max_length=255),
        ),
    ]
