# Generated by Django 5.0 on 2024-04-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0003_registrofinal2_tipo_de_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroformularioempresarial',
            name='tipo_de_negocio',
            field=models.IntegerField(choices=[('Hoteles', 'Hoteles'), ('Restaurantes ', 'Restaurantes '), ('Tiendas de mascotas', 'Tiendas de mascotas'), ('Parques para mascotas', 'Parques para mascotas'), ('Servicios de paseo de perros', 'Servicios de paseo de perros'), ('Destinos Turisticos', 'Destinos Turisticos'), ('Otros', 'Otros')], default='Hoteles', max_length=75, null=True),
        ),
    ]
