# Generated by Django 5.0 on 2025-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0003_alter_registroform_nombre_compania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinal',
            name='nombre_compania',
            field=models.CharField(max_length=255),
        ),
    ]
