# Generated by Django 5.0 on 2025-02-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0004_alter_registrofinal_nombre_compania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofinal',
            name='nombre_compania',
        ),
        migrations.AlterField(
            model_name='registrofinal',
            name='registro_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetSearch.registroform'),
        ),
        migrations.AlterField(
            model_name='registrofinal',
            name='registro_form_empresarial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetSearch.registroformempresarial'),
        ),
    ]
