# Generated by Django 5.0 on 2024-04-22 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0006_registroform_tipo_de_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroform',
            name='fecha_hora_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registroformularioempresarial',
            name='fecha_hora_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
