# Generated by Django 4.2.7 on 2023-11-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0008_auto_20231110_1851'),
    ]

    operations = [
    ]
