# Generated by Django 5.0 on 2024-04-22 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0008_alter_registroformularioempresarial_fecha_hora_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroform',
            name='fecha_hora_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
