# Generated by Django 4.2.7 on 2023-11-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0011_auto_20231110_1857'),
    ]

    operations = [
    ]
