# Generated by Django 4.2.7 on 2023-11-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0012_auto_20231110_1859'),
    ]

    operations = [
    ]
