# Generated by Django 4.2.7 on 2023-11-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0017_auto_20231110_1917'),
    ]

    operations = [
    ]
