# Generated by Django 4.2.7 on 2023-11-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0019_auto_20231110_1926'),
    ]

    operations = [
    ]
