# Generated by Django 4.2.7 on 2023-11-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0020_auto_20231110_1928'),
    ]

    operations = [
    ]
