# Generated by Django 4.2.7 on 2023-11-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0022_auto_20231114_1709'),
    ]

    operations = [
    ]
