# Generated by Django 4.2.7 on 2023-11-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0025_auto_20231114_1736'),
    ]

    operations = [
    ]
