# Generated by Django 4.2.7 on 2023-11-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0027_auto_20231114_1751'),
    ]

    operations = [
    ]
