# Generated by Django 4.2.7 on 2023-11-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0028_auto_20231114_1802'),
    ]

    operations = [
    ]
