# Generated by Django 4.2.7 on 2023-11-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0033_auto_20231114_1853'),
    ]

    operations = [
    ]
