# Generated by Django 4.2.7 on 2023-11-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0034_auto_20231115_1616'),
    ]

    operations = [
    ]
