# Generated by Django 4.2.7 on 2023-11-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0035_auto_20231115_1621'),
    ]

    operations = [
    ]
