# Generated by Django 4.2.7 on 2023-11-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0036_auto_20231115_1728'),
    ]

    operations = [
    ]
