# Generated by Django 4.2.7 on 2023-11-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0037_auto_20231116_1612'),
    ]

    operations = [
    ]
