# Generated by Django 4.2.7 on 2023-11-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0038_auto_20231116_1656'),
    ]

    operations = [
    ]
