# Generated by Django 4.2.7 on 2023-11-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0039_auto_20231116_1706'),
    ]

    operations = [
    ]
