# Generated by Django 4.2.7 on 2023-11-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0040_auto_20231117_1622'),
    ]

    operations = [
    ]
