# Generated by Django 4.2.7 on 2023-11-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0041_auto_20231117_1656'),
    ]

    operations = [
    ]
