# Generated by Django 4.2.7 on 2023-11-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0042_auto_20231120_1658'),
    ]

    operations = [
    ]
