# Generated by Django 4.2.7 on 2023-11-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0043_auto_20231122_1821'),
    ]

    operations = [
    ]
