# Generated by Django 5.0 on 2023-12-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0046_remove_registroform_direccion_registroform_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroform',
            name='latitud',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registroform',
            name='longitud',
            field=models.IntegerField(),
        ),
    ]
