# Generated by Django 5.0 on 2023-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0047_alter_registroform_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroform',
            name='latitud',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registroform',
            name='longitud',
            field=models.CharField(max_length=100),
        ),
    ]
