# Generated by Django 5.0 on 2023-12-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0048_alter_registroform_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroform',
            name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='registroform',
            name='telefono_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
