# Generated by Django 5.0 on 2023-12-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0049_remove_registroform_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroformularioempresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(max_length=75)),
                ('telefono_usuario', models.IntegerField(blank=True, null=True)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
            ],
        ),
    ]
