# Generated by Django 5.0 on 2023-12-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0050_registroformularioempresarial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroformularioempresarial',
            name='nombre_de_quien_registra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
