# Generated by Django 5.0 on 2023-12-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0051_registroformularioempresarial_nombre_de_quien_registra'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroform',
            name='correo_electronicoform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registroform',
            name='nombre_compañiaform',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
