# Generated by Django 5.0 on 2023-12-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0052_registroform_correo_electronicoform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrototal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(blank=True, max_length=75, null=True)),
                ('telefono_usuario', models.IntegerField(blank=True, null=True)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(blank=True, max_length=100)),
                ('nombre_de_quien_registra', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registroform',
            name='nombre_compañiaform',
            field=models.CharField(max_length=75),
        ),
    ]
