# Generated by Django 5.0 on 2023-12-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0053_registrototal_alter_registroform_nombre_compañiaform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroform',
            name='correo_electronicoform',
        ),
        migrations.RemoveField(
            model_name='registroform',
            name='nombre_compañiaform',
        ),
    ]
