# Generated by Django 5.0 on 2023-12-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0054_remove_registroform_correo_electronicoform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrototal',
        ),
    ]
