# Generated by Django 5.0 on 2023-12-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0055_delete_registrototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroform',
            name='longitud',
            field=models.CharField(max_length=75),
        ),
    ]
