# Generated by Django 5.0 on 2023-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0056_alter_registroform_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrofinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(max_length=150)),
                ('latitud', models.CharField(max_length=150)),
                ('longitud', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=150)),
                ('telefono_usuario', models.IntegerField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
