# Generated by Django 5.0.1 on 2024-01-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0057_registrofinal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrofinal',
        ),
    ]
