# Generated by Django 5.0.1 on 2024-01-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0058_delete_registrofinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrofinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(max_length=150)),
                ('latitud', models.CharField(max_length=150)),
                ('longitud', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=150)),
                ('telefono_usuario', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
