# Generated by Django 5.0.1 on 2024-01-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0059_registrofinal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrofinal',
            new_name='registrofinal2',
        ),
    ]
