# Generated by Django 5.0.1 on 2024-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0060_rename_registrofinal_registrofinal2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinal2',
            name='correo_electronico',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
