# Generated by Django 5.0.1 on 2024-01-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSearch', '0061_alter_registrofinal2_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroform',
            name='telefono_usuario',
            field=models.IntegerField(blank=True, max_length='12', null=True),
        ),
        migrations.AlterField(
            model_name='registroformularioempresarial',
            name='telefono_usuario',
            field=models.IntegerField(blank=True, max_length='12', null=True),
        ),
    ]
