# Generated by Django 5.0 on 2024-02-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_ciudad_appuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
