# Generated by Django 5.0 on 2024-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='foto',
            field=models.CharField(blank=True, null=True),
        ),
    ]
