name: Docker Image CI

on:
  push:
    branches: [ "Cristian" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare tag
      id: prep
      run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)"

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cristian7b/zonapets:${{ steps.prep.outputs.tag }}

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the Docker image
      run: |
        docker push cristian7b/zonapets:${{ steps.prep.outputs.tag }}

    - name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
